### ISSUE TITLE
allow field redaction

### ISSUE THREAD

**Issue by tmc** [tmc/pqstream#1]
should supply a capability to redact some fields

**Comment by pieterlouw** [comment]
@tmc, would this be from client or server?

**Comment by tmc** [comment]
I was thinking in the context of sensitive values -- server.

**Comment by pieterlouw** [comment]
How will this need to be specified? By config file (i.e TOML) or cli flags?

If it's many fields that need to be specified then config file makes more sense

**Comment by tmc** [comment]
I think the typical use case would be a small number of fields. I'd prefer
to try to hold off on config file for simplicity.

**Comment by tmc** [comment]
Perhaps we come up with a field addressing means such as
"(schema).(table).(field)"

**Comment by pieterlouw** [comment]
Something like: `--flags table1.field1,table2.{field1,field3}` ?

**Comment by tmc** [comment]
Yeah something like that `--redactions=public.users.password,public.users.equifax_ssn`

**Comment by pieterlouw** [comment]
Doh, I meant --fields, not --flags.

Is `user.{password, ssn}` okay for multiple fields in one table?

**Comment by tmc** [comment]
that seems harder to parse but I'm open to it if the implementation is simple.

**Comment by pieterlouw** [comment]
Okay.I'll pick up this one and implement.

Not sure what other simpler way to give the user to specify multiple fields for a table

**Comment by tmc** [comment]
Fixed via #17
