### ISSUE TITLE
UPDATE should send both OLD and NEW values

### ISSUE THREAD

**Issue by xentek** [tmc/pqstream#21]
UPDATE statements should send OLD and NEW so that you can compare values (e.g. dirty fields) and take action on the payload if a field of interest has changed.

**Comment by xentek** [comment]
Great looking project. Can't wait to see how this develops.

**Comment by tmc** [comment]
@xentek thanks for your interest. I think there are a couple of ways this could happen -- do you want to propose a modified API? I could see some folks not wanting diffs but I agree it's probably a common ask. We could either ship a json patch payload along side the row that was modified or ship full versions of both. Either way the api needs to be extended.

**Comment by tmc** [comment]
https://godoc.org/github.com/evanphx/json-patch looks like a decent library that could be used here.

**Comment by xentek** [comment]
@tmc `json-patch` looks great and what I've seen in #22 exceeds my expectations. Can't wait to play with it more this weekend. cheers!

**Comment by tmc** [comment]
@xentek we chat in #pqstream oh https://invite.slack.golangbridge.org/ -- we would love to hear about possible use cases!
