### ISSUE TITLE
ci: add linting to ci

### ISSUE THREAD

**Issue by tmc** [tmc/pqstream#38]
consider gometalinter, at least go vet + golint

**Comment by joaodrp** [comment]
Hi @tmc, is this still required? I can see that you already have `gometalinter` in the lint script, which is invoked by the circle ci.

**Comment by tmc** [comment]
Oh yeah this is done. I wanted to have some structure in place to help guide contributions. Thanks for your interest and please jump in elsewhere!!

Right now linting is the slowest step in ci so that is a place I'd love some help!
