### ISSUE TITLE
add gops functionality to cli apps

### ISSUE THREAD

**Issue by pieterlouw** [tmc/pqstream#50]
Add [gops](https://github.com/google/gops) functionality to diagnose and profile cli app processes

**Comment by tmc** [comment]
Does this require any code modifications? I was under the impression gops worked with any existing binary.

**Comment by tmc** [comment]
oh I see https://github.com/google/gops#diagnostics now

**Comment by alileza** [comment]
anyone working on this?

**Comment by tmc** [comment]
@alileza no I don't think so

**Comment by tmc** [comment]
Pieter might have started
