### ISSUE TITLE
demonstrate clients in other languages

### ISSUE THREAD

**Issue by tmc** [tmc/pqstream#57]
let's implement some basic clients in `clients/${lang}` directories

- [x] python https://github.com/tmc/pqstream/issues/59
- [ ] ruby https://github.com/tmc/pqstream/issues/60
- [x] node https://github.com/tmc/pqstream/issues/61

**Comment by andrefreitas** [comment]
Hi, I believe I could help you in this, just need to evaluate the work to be done. 

The goals are generating Python and Ruby clients from the `pqstream.proto` and create documentation for these clients, right?

**Comment by pieterlouw** [comment]
Node.js client can also be considered.

Travis, would these clients be in a different repo or   live under a `clients` subfolder under this repo?

**Comment by pieterlouw** [comment]
Hi @andrefreitas. Thanks! 
Yes that's correct.

**Comment by tmc** [comment]
@pieterlouw I think they should live in this repo for now. clients/langs seems like a fine subdirectory.

**Comment by eraclitux** [comment]
@andrefreitas let me know if you want help with the Python client

**Comment by tmc** [comment]
let's open issues for the different languages

**Comment by andrefreitas** [comment]
I think we can close this issue :)

**Comment by tmc** [comment]
Thanks!
