### ISSUE TITLE
ci: add circle job to test python client

### ISSUE THREAD

**Issue by tmc** [tmc/pqstream#63]
- [x] basic tests
- [x] linting

**Comment by tmc** [comment]
@ofosos would you be interested in this?

**Comment by ofosos** [comment]
Jup, but may take some time (sunday?).

**Comment by tmc** [comment]
Awesome. I may get something basic in place before then to guide additional contributions

**Comment by tmc** [comment]
I think we can consider this done given the state of the python circle job. Getting real unit and integration tests into place would be awesome but this issue aimed for an initial (lower) target.
